# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "http://localhost:5000/"
title = "Jane - A super concise theme for Hugo"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 3              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓



# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages]
  [languages.en]
    title = "Malanada Mahadevar temple"
    languageName = "English"
    weight = 1
  [languages.ml]
    title = "മലനട മഹാദേവർ ക്ഷേതൃം"
    languageName = "മലയാളം"
    weight = 2


[author]                  # essential                     
  name = "Malanada Mahadevar Temple"

[sitemap]                 # essential                     
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  since = "2020"            # Site creation time          
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  
  #logoTitle = "മലനട മഹാദേവർ ക്ഷേതൃം"        # default: the title value    
  keywords = ["Malanada", "Mahadevar","temple"]
  description = "മലനട മഹാദേവർ ക്ഷേതൃം"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe           
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  showMenuLanguageChooser= true

  [params.social]                                        
    a-email = "mailto:your@email.com"
    d-facebook = "http://localhost:1313"

